
FROM golang:1.25-alpine AS build

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY cmd ./cmd
COPY service ./service
COPY doc ./doc

RUN go build -o /bin/webapi ./cmd/webapi



FROM alpine:3.20
WORKDIR /app


RUN apk add --no-cache ca-certificates

COPY --from=build /bin/webapi /app/webapi

EXPOSE 3000
CMD ["/app/webapi"]
