
    FROM golang:1.25-alpine AS build
    WORKDIR /app
    
    RUN apk add --no-cache git
    
 
    COPY backend/go.mod backend /
    RUN go mod download
    
   
    COPY backend/ ./
    
  
    RUN CGO_ENABLED=0 GOOS=linux go build -o webapi ./cmd/webapi
    
  
    FROM alpine:3.20
    WORKDIR /app
    COPY --from=build /app/webapi /app/webapi
    
    EXPOSE 3000
    CMD ["/app/webapi"]